//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CukCuk.Core.MISAResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CukCuk.Core.MISAResources.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Code.
        /// </summary>
        public static string Employee_EmployeeCode {
            get {
                return ResourceManager.GetString("Employee_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Full name.
        /// </summary>
        public static string Employee_EmployeeName {
            get {
                return ResourceManager.GetString("Employee_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, please contact Misa for support.
        /// </summary>
        public static string Erorr_Exception {
            get {
                return ResourceManager.GetString("Erorr_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department ID Not Valid.
        /// </summary>
        public static string Error_DepartmentIDNotValid {
            get {
                return ResourceManager.GetString("Error_DepartmentIDNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Value Not Valid.
        /// </summary>
        public static string Error_InputValueNotValid {
            get {
                return ResourceManager.GetString("Error_InputValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position ID is invalid.
        /// </summary>
        public static string Error_PositionIDNotValid {
            get {
                return ResourceManager.GetString("Error_PositionIDNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not valid!.
        /// </summary>
        public static string Error_ValidateData {
            get {
                return ResourceManager.GetString("Error_ValidateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Gender_Other {
            get {
                return ResourceManager.GetString("Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee deleted successfully.
        /// </summary>
        public static string Info_EmployeeDeleted {
            get {
                return ResourceManager.GetString("Info_EmployeeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Not Found.
        /// </summary>
        public static string Info_EmployeeNotFound {
            get {
                return ResourceManager.GetString("Info_EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateOfBirth is not valid!.
        /// </summary>
        public static string ValidateError_DateOfBirthNotValid {
            get {
                return ResourceManager.GetString("ValidateError_DateOfBirthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not valid!.
        /// </summary>
        public static string ValidateError_EmailNotValid {
            get {
                return ResourceManager.GetString("ValidateError_EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EmployeeCode already exists.
        /// </summary>
        public static string ValidateError_EmployeeCodeExits {
            get {
                return ResourceManager.GetString("ValidateError_EmployeeCodeExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode empty is not allow.
        /// </summary>
        public static string ValidateError_EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("ValidateError_EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName empty is not allow.
        /// </summary>
        public static string ValidateError_FullNameNotEmpty {
            get {
                return ResourceManager.GetString("ValidateError_FullNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not allow null.
        /// </summary>
        public static string ValidateError_NotNull {
            get {
                return ResourceManager.GetString("ValidateError_NotNull", resourceCulture);
            }
        }
    }
}
